### ISSUE TITLE
how to use on react with Typescipt

### ISSUE THREAD

**Issue by qisirui99** [launchdarkly/react-client-sdk#15]
I try to use the launchdarkly-react-client-sdk on my react project that is developed by Typescript.
when I use the below code. It said "Parameter 'flags' implicitly has an 'any' type." and even if I add the any type to flags, it also error. could anyone tell me how to use the library on react with Typescript? Thank you for advance!
const HomeViewTop = (flags) => {
    return (
        flags.ph3 ? <div>Flag on</div> : <div>Flag off</div>
    )
}

**Comment by bwoskow-ld** [comment]
Hi @qisirui99,

You should be able to use the `LDFlagSet` type instead of `Any` to represent `flags`. I believe that'll unblock you however without knowing more about how you're using the React SDK, I can't say for certain. For example, it would be helpful to know which API you're using from the React SDK, the greater context of the above code snippet, and your SDK version.

This issue tracker is only meant for bug reports and feature requests. To get assistance with using LaunchDarkly's SDKs, please raise a support request with the LaunchDarkly support team at support@launchdarkly.com. If you need additional assistance and can provide them with more information (as mentioned in my first paragraph), they'd be happy to help you out.

Cheers,
Ben
