### ISSUE TITLE
camelCasing flag keys when switching the user context

### ISSUE THREAD

**Issue by rathesDot** [launchdarkly/react-client-sdk#19]
**Describe the bug**
Not really sure if this is a bug report or if I'm just missing a hint to the right direction in the docs.

I use the `withLDConsumer()` in a component of mine to get the `ldClient` from the props to switch the user-context using `ldClient.identify()` as described here: https://docs.launchdarkly.com/docs/js-sdk-reference#section-changing-the-user-context

In the callback (or after awaiting the promise), I want to use the new feature flags map to perform more actions (such as passing them to another service).

The problem is that the returned value of the new flags is not camelCased but returns the original value.

**To reproduce**

ldclient.identify(newUser, hash, (_, newFlags) => {
  console.log(newFlags);
});

Here the new flags key would be something like `domain.some-feature` ...

**Expected behavior**

In the context, the value for the flag above would be stored as `domainSomeFeature` so that I could access is as `flags.domainSomeFeature` in the components

**SDK version**
2.15.1

**Comment by bwoskow-ld** [comment]
Hi @rathesDot,

You're correct in that `newFlags` in your example will not necessarily contain camel-cased keys. These flag keys will equal the format known to [app.launchdarkly.com](https://app.launchdarkly.com). The only case in which `newFlags` will have camel-cased keys is if the keys are set to be camel-cased on LaunchDarkly's site upon flag creation.

There's some technical context I need to explain in order to walk through the problem. LaunchDarkly offers a [JavaScript SDK](https://github.com/launchdarkly/js-client-sdk) for browser-based JS. Additionally, LaunchDarkly offers [this SDK](https://github.com/launchdarkly/react-client-sdk) for folks using ReactJS. However, the React SDK isn't a standalone SDK; it is actually just a simple wrapper around the JavaScript SDK, incorporating some React-specific items for a tighter developer experience. The core functionality (more specifically -- all functionality accessible from the `ldclient` object) is exposed from the JavaScript SDK.

With that context in place... I'd like to direct you to our documentation section on [flag keys in the React SDK](https://docs.launchdarkly.com/docs/react-sdk-reference#section-flag-keys) which describes this problem quite well. If I was to write about the problem here, I'd just be repeating the doc. The one thing I'd like to add is that this problem isn't specific to `identify` -- for example, `ldClient.allFlags` will also return flags keys in their original format.

You have a couple ways to work around this:

1. Disable auto-camel-casing if you are comfortable with doing so. Obviously this will have a ripple effect across your entire application wherever you access flags.
2. Access your flags via props or hooks instead of through the `identify` closure.

Let me know if this satisfactorily answers your question.

Cheers,
Ben

**Comment by rathesDot** [comment]
Hi Ben,

thank you very much for your very detailed answer, it helps me a lot and it was exactly what I was expected to get as an answer.

The problem with 

> Access your flags via props or hooks instead of through the identify closure.

is, however, that I am calling the `identify` call in the `componentDidMount` function and I have to make some other calls to some other services based on the result of the flags-call.

My workaround now is that I copied the camelCaseKeys (https://github.com/launchdarkly/react-client-sdk/blob/master/src/utils.ts#L12) functionality into my application and camelCase them manually.

It would be helpful if the helper method was exported from this package, then changes in your helper would not affect my code-base.

Thanks again for your help,
Rathes

**Comment by bwoskow-ld** [comment]
Hi @rathesDot,

Exporting our camel-case utility function seems like a reasonable suggestion to help make your code more maintainable. I've gone ahead and made this change on our private mirror. It'll be included in the next SDK release. I'll leave this issue open until that's available.

Cheers,
Ben

**Comment by bwoskow-ld** [comment]
Hi @rathesDot,

This is now available in version [2.17.0](https://github.com/launchdarkly/react-client-sdk/releases/tag/2.17.0).

Let me know if there's anything else!

Ben

**Comment by rathesDot** [comment]
Thank you Ben for helping out that quickly!
