### ISSUE TITLE
Question: how to use `flags` option in LD provider initialization

### ISSUE THREAD

**Issue by obedparla** [launchdarkly/react-client-sdk#29]
👋 hi!

I tried finding the answer to this in the docs and source code, plus tried a few things in the code, but I couldn't figure out how the `flags` option of the `withLDProvider` works.

The documentation states: `If specified, launchdarkly-react-client-sdk will only request and listen to these flags. Otherwise, all flags will be requested and listened to.`

After checking the source code in the JS sdk, I confirmed it's expecting an array. I tried using: `{flags: ['camelCaseNameOfMyFlag] }` and `{flags: ['normal-name-of-my-flag'] }` but in both cases what I get when using `useFlags()` is `{ 0: "camelCaseNameOfMyFlag" }`, and not the actual value of the flag in LaunchDarkly.

Not specifying any `flags` option gives me all flags as expected so I know my implementation works.

Could someone clarify how to use this option? I'd be happy to open some PR for the documentation afterward.

**Comment by bwoskow-ld** [comment]
Hi @obedparla,

That's a good question. I looked over [our documentation](https://docs.launchdarkly.com/sdk/client-side/react#configuring-the-react-sdk) and confirmed that what we've provided is lacking. While I don't mind improving the docs myself, I don't want to take away your opportunity to get credit for the doc contribution (if you want it), and so I'd be happy to let you make the changes if you prefer. You would be submitting a pull request for modifications on [this file](https://github.com/launchdarkly/LaunchDarkly-Docs/blob/master/src/content/topics/sdk/client-side/react.mdx).

As for how the `flags` configuration option works -- it expects a map of flag keys and values. The flag keys must be in their original form (as known to LaunchDarkly) rather than in their camelCased form. This is true regardless of if the [`useCamelCaseFlagKeys: false` option](https://docs.launchdarkly.com/sdk/client-side/react#flag-keys) is set. The flag values will be passed along to the resulting JS SDK [`variation`](https://docs.launchdarkly.com/sdk/client-side/javascript#variation) invocation and used as the flag's default value in case of an error occurring.

Putting this all together, a concrete example of how `flags` should be constructed is:

```js
{
    'my-bool-flag': true,
    'my-int-flag': 5
}
```

Let me know about proceeding with the documentation improvement; if I don't hear from you in the next couple days, I'll go ahead and make the doc change myself.

Cheers,
Ben

**Comment by obedparla** [comment]
Hey, @bwoskow-ld thank you for the clear explanation! 

Did you make the change to the docs? I read this the same day and set about to do the PR and then life happened 😅 i

**Comment by bwoskow-ld** [comment]
Yes, I have a pull request up on our private docs mirror. I'll close this ticket when the doc update has gone live.

**Comment by bwoskow-ld** [comment]
The docs update is now available on https://docs.launchdarkly.com/sdk/client-side/react#configuring-the-react-sdk. Cheers!

**Comment by VishalKatharotiya** [comment]
Hey @bwoskow-ld I tried with the below code.

```
  clientSideID: process.env.LAUNCHDARKLY_PROJECT_CLIENT_SIDE_ID || '',
  user: {
    key: user?.uid,
    name: user?.email,
    email: user?.email,
  },
  reactOptions: {
    useCamelCaseFlagKeys: false,
  },
  flags: { 'test-vk': false },  //Default set value to false
```
here, if LD initialization failed, **test-vk** seems undefined instead of the default false value as I have set in the flags attribute. 
1. Is there any way to set the default value to flag incase of LD initialization failed
