### ISSUE TITLE
All keys being evaluated and returned when requesting specific ones

### ISSUE THREAD

**Issue by obedparla** [launchdarkly/react-client-sdk#33]
**Describe the bug**
Hey guys,

Whenever a connection is made with `withLDProvider` using the `flags` option, all keys are evaluated in LaunchDarkly, and all of them are returned in the network response, even though only the requested one in the `flags` option is available through the code.

I'm not sure if this is intended behavior, I'm doing something wrong, or if it's a bug. But clarification would be greatly appreciated 🙏. I'm assuming it's a bug because the documentation states

> flags: If specified, the React SDK will only request and subscribe for updates to these flags. The React SDK will request for and subscribe to all flags when this property is unspecified. This property is optional.

Docs [here](https://docs.launchdarkly.com/sdk/client-side/react#configuring-the-react-sdk)

**To reproduce**
Here's my code:

```
const MyExtendedComp = withLDProvider({
  clientSideID: clientsideId,
  user: {
    key: userKey,
    custom: {
      'operator-id': operatorId,
    },
  },
  flags: {
    'admin-my-key': false,
  },
})(MyComponent);
```

**Expected behavior**
I'd expect that LD only evaluates and returns the flag I'm requesting. In this case `admin-my-key` and not all of them only to filter it out in the client.

**SDK version**
"launchdarkly-react-client-sdk": "^2.18.0",

**Comment by obedparla** [comment]
I landed on this issue https://github.com/launchdarkly/js-client-sdk/issues/193#issuecomment-562274718 on the JS SDK, and they explain that the flags are always evaluated, but that the analytics will only be affected by the flags _we request_. Can someone confirm this is the case?

**Comment by bwoskow-ld** [comment]
Hi @obedparla,

What you've described is intended behavior. The entire flag set, regardless of whether or not individual flags are specified in the `flags` property, are included in the requests between LaunchDarkly and your SDK instance on SDK initialization and on changing users. The filtering happens within the React SDK as a post-function after those flags are received from LaunchDarkly.

You're correct in calling out a mistake in our docs. I remember personally adding that doc content when we [last spoke](https://github.com/launchdarkly/react-client-sdk/issues/29) on this topic. I'll submit a PR to update the docs so that it doesn't say that the SDK will only request for specified flags.

**Comment by obedparla** [comment]
Cheers, thank you for the clarification @bwoskow-ld. 

Is it correct to assume that the analytics are not affected by this, and only the requested flags will be recorded as  "used"? 

I'll do some validation on our end to make sure this is the case, but I'd like to confirm the intended behavior of the SDK

**Comment by bwoskow-ld** [comment]
That is correct. Analytics (evaluation events) are sent once per flag in the `flags` object. Flags not specified in this object will not have corresponding events published to LaunchDarkly.

**Comment by obedparla** [comment]
Thank you for clarifying! Have a great day :)
