### ISSUE TITLE
Server-side rendering support

### ISSUE THREAD

**Issue by katia-aa** [launchdarkly/react-client-sdk#42]
**Is your feature request related to a problem? Please describe.**
I am using Next.js and wasn't able to take advantage of server-side rendering for LD setup. 

**Describe the solution you'd like**
Would love to see the SDK offer support to server-side rendering. 

**Describe alternatives you've considered**
I tried using the client-side Node SDK in Next.js server but that didn't work.

**Additional context**
Our users are experiencing "flickering" on our app and we couldn't use the async provider due to the way Next.js app structure.

**Comment by eli-darkly** [comment]
> I tried using the client-side Node SDK in Next.js server but that didn't work.

It's hard to respond to this issue if we don't know 1. specifically how you tried using it, 2. why you were using the _client-side_ Node SDK in a server context, and 3. specifically how it didn't work.

**Comment by katia-aa** [comment]
That's fair, I did try both the client-side and server-side Node SDKs. When I imported the server-side Node SDK in Next.js server, it didn't work and gave me an error: `LaunchDarkly.initialize is not a function`.

I then looked into the client-side Node SDK and decided to try it; it initialized successfully and I could print the flags in the server but I wasn't able to pass them back to the client the way I could other data. I think it was because after initializing the SDK, I had to use ```ldClient.on('ready', () => { ... }``` callback and that wasn't playing well, so setting a variable in the callback after SDK was ready did not work as the data came back to the client `undefined`. 

Also worth noting that importing client-side Node SDK into [getInitialProps](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps) - server-side rendering function in Next.js - caused the app to re-render an extra time.

**Comment by bwoskow-ld** [comment]
Hi @katia-aa ,

I'd like to continue investigating if the [Node Server-Side SDK](https://github.com/launchdarkly/node-server-sdk) would meet your needs here for bootstrapping flags onto your Next.js-based pages. You mentioned that `LaunchDarkly.initialize` wasn't a function. That's because the API semantics may vary across our SDKs. Per our [documentation](https://docs.launchdarkly.com/sdk/server-side/node-js#getting-started) you'll actually want to call `LaunchDarkly.init("YOUR_SDK_KEY")` to get started with the Node Server-Side SDK. Can you give this a try again at your earliest convenience?

Regarding which SDK to look into -- the Node Server-Side SDK and Node Client-Side SDKs operate in fundamentally different ways. I could explain the difference here.... but as [our documentation](https://docs.launchdarkly.com/sdk/concepts/client-side-server-side#understanding-the-different-types-of-sdks) does a fair job of that, I'll instead point you there. You'll probably find that the server-side SDK is more suited for your needs given that you're rendering on your server.

**Comment by katia-aa** [comment]
Thanks. We ended up going with Google Optimize
