### ISSUE TITLE
Failed XHR Request

### ISSUE THREAD

**Issue by Dnguye92** [launchdarkly/react-client-sdk#65]
**Describe the bug**
On our next.js application we're seeing a cancelled request to `https://clientstream.launchdarkly.com/eval/*`. We're using Sentry to log our errors and what we're seeing in Sentry is `LaunchDarklyFlagFetchError __webpack_require__(chunks/webpack/bootstrap)`.

**To reproduce**
Loading any page on our next.js application

**Expected behavior**
No failed requests

**Logs**
On the browser network tab: Not much information - just shows the request as `cancelled` with a type of `eventsource`.
On Sentry: `LaunchDarklyFlagFetchError __webpack_require__(chunks/webpack/bootstrap)`

**SDK version**
`2.21.0`

**Language version, developer tools**
```
"next": "^10.0.6",
"launchdarkly-react-client-sdk": "^2.21.0",
"typescript": "^4.0.2"
```

**OS/platform**
Chrome, Firefox, Safari all versions

**Comment by bwoskow-ld** [comment]
Hi @Dnguye92 ,

I'm going to direct you to our support team at support@launchdarkly.com to help you resolve this issue. This issue tracker is intended for bugs and feature requests for this SDK, and while your request may be due to an underlying bug, it needs further diagnosis first which our support team would be happy to assist with. On the support ticket you'll be able to privately discuss your SDK configuration, identify any potential networking issues, and so forth which may be relevant to your particular issue.

Cheers,
@bwoskow-ld
